### ISSUE TITLE
Reboot from Home Assistant causes stack trace and control to cease. Typo?

### ISSUE THREAD

**Issue by thewishy** [britkat1980/giv_tcp#124]
Version 2.2.0 in a container

The battery was doing something weird, so i requested a reboot via givtcp. (Turns out, it decided that 4kWh was actually empty, hence the battery idled at 100w, which seemed weird at the time as the battery SOC didn't drop until half hour later).

Sending the inverter reboot caused givtcp to stack trace, which caused any further commands to be ignored (Battery didn't charge overnight)

Restarting the container resolved. Stack trace suggests an inverter vs invertor typo could be the cause?..

Traceback (most recent call last):
  File "/app/GivTCP_1/mqtt_client.py", line 231, in <module>
    client.loop_forever()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/app/GivTCP_1/mqtt_client.py", line 63, in on_message
    wr.rebootinvertor()
AttributeError: module 'write' has no attribute 'rebootinvertor'. Did you mean: 'rebootinverter'?

**Comment by britkat1980** [comment]
fixed in version 2.4.0
