### ISSUE TITLE
Since updating to 2.3.2 Solcast forecast and SoC setting has failed.

### ISSUE THREAD

**Issue by Yorkie71** [britkat1980/giv_tcp#99]
Previously working perfectly, since 2.3.2 the SoC has not been and a quick look of the log, while I'm no expert here, doesn't look to healthy. In addition to the IndexError on the palm_soc section, there are increase connection errors. While I'm used to seeing a few, they seem to have increased.

Inverter F/W : D0.450-A0.451
Inverter model: GIV-HY3.6
Battery F/W: 3013
Battery model: 8.2kWh

I have the old inverter firmware switch enabled.

-------------------------------------
Extract from log.
2023-08-03 00:20:11,354 - Inv1 - palm_soc    -  [INFO    ] - Successful Solcast download.
2023-08-03 00:20:11,358 - Inv1 - palm_soc    -  [INFO    ] - Applying BST offset to Solcast data
Traceback (most recent call last):
  File "/app/GivTCP_1/palm_soc.py", line 704, in <module>
    solcast.update()
  File "/app/GivTCP_1/palm_soc.py", line 619, in update
    pv_est10[i] = int(solcast_data_1['forecasts'][cntr]['pv_estimate10'] * 1000)
IndexError: list index out of range
2023-08-03 00:30:03,683 - Inv1 - read        -  [INFO    ] - Saving current energy stats at start of night rate tariff (Dynamic)
2023-08-03 00:56:15,773 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 00:56:18,288 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 01:45:21,410 - Inv1 - read        -  [ERROR   ] - Battery Object empty so skipping
2023-08-03 01:50:23,457 - Inv1 - read        -  [ERROR   ] - Battery Object empty so skipping
2023-08-03 01:55:25,048 - Inv1 - read        -  [ERROR   ] - Battery Object empty so skipping
2023-08-03 01:56:25,325 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 01:56:27,837 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 01:56:41,497 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 02:32:17,967 - Inv1 - write       -  [INFO    ] - Disabling Discharge
2023-08-03 02:32:22,042 - Inv1 - write       -  [INFO    ] - Setting shallow charge 100 was a success
2023-08-03 02:34:57,601 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 03:01:52,173 - Inv1 - write       -  [INFO    ] - Enabling Discharge
2023-08-03 03:01:55,935 - Inv1 - write       -  [INFO    ] - Setting shallow charge 4 was a success
2023-08-03 03:15:16,819 - Inv1 - read        -  [ERROR   ] - Consecutive failure count= 4 -- (<class 'Exception'>, Exception("Garbage or failed inverter Response: ERROR:-(<class 'KeyError'>, KeyError(IR:110), <traceback object at 0x7fac371ac0>)"), <traceback object at 0x7f9e152380>)
2023-08-03 03:15:28,567 - Inv1 - read        -  [ERROR   ] - Consecutive failure count= 5 -- (<class 'Exception'>, Exception("Garbage or failed inverter Response: ERROR:-(<class 'KeyError'>, KeyError(HR:113), <traceback object at 0x7fac371cc0>)"), <traceback object at 0x7f9c8b1680>)
2023-08-03 03:15:40,783 - Inv1 - read        -  [ERROR   ] - Consecutive failure count= 6 -- (<class 'Exception'>, Exception("Garbage or failed inverter Response: ERROR:-(<class 'KeyError'>, KeyError(HR:013), <traceback object at 0x7fac371d40>)"), <traceback object at 0x7f9cbaf180>)
2023-08-03 03:15:52,092 - Inv1 - read        -  [ERROR   ] - Consecutive failure count= 7 -- (<class 'Exception'>, Exception("Garbage or failed inverter Response: ERROR:-(<class 'KeyError'>, KeyError(HR:013), <traceback object at 0x7fac371c00>)"), <traceback object at 0x7f9cb78340>)
2023-08-03 03:19:42,898 - Inv1 - read        -  [ERROR   ] - Consecutive failure count= 4 -- (<class 'Exception'>, Exception("Garbage or failed inverter Response: ERROR:-(<class 'KeyError'>, KeyError(IR:110), <traceback object at 0x7fac35d340>)"), <traceback object at 0x7f9e15f1c0>)
2023-08-03 03:20:49,408 - Inv1 - read        -  [ERROR   ] - Consecutive failure count= 4 -- (<class 'Exception'>, Exception("Garbage or failed inverter Response: ERROR:-(<class 'KeyError'>, KeyError(IR:183), <traceback object at 0x7fac35dcc0>)"), <traceback object at 0x7f9d808380>)
2023-08-03 03:22:28,463 - Inv1 - read        -  [ERROR   ] - Consecutive failure count= 4 -- (<class 'Exception'>, Exception("Garbage or failed inverter Response: ERROR:-(<class 'KeyError'>, KeyError(HR:013), <traceback object at 0x7fac365e00>)"), <traceback object at 0x7f9c889a80>)
2023-08-03 03:26:36,799 - Inv1 - read        -  [ERROR   ] - Consecutive failure count= 4 -- (<class 'Exception'>, Exception("Garbage or failed inverter Response: ERROR:-(<class 'KeyError'>, KeyError(HR:013), <traceback object at 0x7fac35dbc0>)"), <traceback object at 0x7f9e44ca40>)
2023-08-03 03:31:50,759 - Inv1 - write       -  [INFO    ] - Disabling Discharge
2023-08-03 03:31:54,366 - Inv1 - write       -  [INFO    ] - Setting shallow charge 100 was a success
2023-08-03 03:55:50,780 - Inv1 - write       -  [INFO    ] - Enabling Discharge
2023-08-03 03:55:54,460 - Inv1 - write       -  [INFO    ] - Setting shallow charge 4 was a success
2023-08-03 04:30:09,424 - Inv1 - read        -  [INFO    ] - Saving current energy stats at start of day rate tariff (Dynamic)
2023-08-03 04:51:33,412 - Inv1 - read        -  [ERROR   ] - Battery Object empty so skipping
2023-08-03 04:56:35,233 - Inv1 - read        -  [ERROR   ] - Battery Object empty so skipping
2023-08-03 05:26:45,884 - Inv1 - read        -  [ERROR   ] - Battery Object empty so skipping
2023-08-03 05:31:47,950 - Inv1 - read        -  [ERROR   ] - Battery Object empty so skipping
2023-08-03 05:38:54,422 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 06:52:33,310 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 07:07:22,172 - Inv1 - read        -  [ERROR   ] - Battery Object empty so skipping
2023-08-03 07:17:26,036 - Inv1 - read        -  [ERROR   ] - Battery Object empty so skipping
2023-08-03 07:39:21,444 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 08:06:52,481 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 08:19:03,638 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out
2023-08-03 08:19:06,156 - Inv1 - sync        -  [ERROR   ] - Connection to (192.168.1.117, 8899) failed: timed out

**Comment by salewis38** [comment]
Fix already provided as pull request #97
